name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: setup depot-tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: fetch
        run: |
          fetch devtools-frontend
      - name: build
        working-directory: devtools-frontend
        run: |
          gclient sync
          gn gen out/Default
          autoninja -C out/Default
      - name: version
        id: get_version
        working-directory: devtools-frontend
        run: |
          # commit position number
          POSITION=$(git rev-list --count HEAD)
          # format version as 1.0.{commit-position}
          FULL_VERSION="1.0.${POSITION}"
          echo "Setting version to $FULL_VERSION"
          echo "version=$FULL_VERSION" >> $GITHUB_OUTPUT
          cd ..
          # check if the version is already in the package.json
          if ! grep -q "\"version\": \"$FULL_VERSION\"" package.json; then
            # update package.json with the new version
            npm version $FULL_VERSION --no-git-tag-version
            git add package.json package-lock.json
            git commit -m "chore: update version"
            git push
          fi

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}