name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup depot-tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: fetch
        run: |
          fetch --no-history devtools-frontend
      - name: build
        run: |
          cd devtools-frontend
          gclient sync
          gn gen out/Default
          autoninja -C out/Default
      - name: version
        id: get_version
        run: |
          # commit position number
          POSITION=$(git rev-list --count HEAD)
          # format version as 1.0.{commit-position}
          FULL_VERSION="1.0.${POSITION}"
          echo "Setting version to $FULL_VERSION"
          cd ..
          echo "version=$FULL_VERSION" >> $GITHUB_OUTPUT
          # update package.json with the new version
          npm version $FULL_VERSION --no-git-tag-version
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}